# Generated by Django 4.2.6 on 2023-11-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
